api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "remove-zero-price"
type = "function"
uid = "0197fff7-7b8c-d3c7-d971-eeac3444bf6e83630134"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
