# Learn more about configuring your checkout UI extension:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration

api_version = "2026-01"

[[extensions]]
name = "remove-zero-price-checkout"
handle = "remove-zero-price-checkout"
type = "ui_extension"
uid = "b39858e7-1e9c-a483-b6ab-24ea26f87b9b234efe71"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
cart_line_items_change = true

[[extensions.metafields]]
namespace = "custom"
key = "parent_product"
